# Generated by Django 5.0.6 on 2024-07-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_delete_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
