# Generated by Django 5.0.6 on 2024-07-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='photo',
            field=models.ImageField(default='../media/media/logo.png', upload_to='profile_photos/'),
        ),
    ]
