# Generated by Django 5.0.6 on 2024-07-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_notes_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='photo',
            field=models.ImageField(default='media/logo.png', upload_to='profile_photos'),
        ),
    ]
