# Generated by Django 5.0.6 on 2024-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
