# Generated by Django 5.0.6 on 2024-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default=2, max_length=7),
            preserve_default=False,
        ),
    ]
