# Generated by Django 5.0.6 on 2024-07-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='prerequisites',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
