# Generated by Django 5.0.6 on 2024-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
