# Generated by Django 5.0.6 on 2024-07-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_notes_prerequisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='prerequisites',
        ),
    ]
