# Generated by Django 5.0.6 on 2024-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_notes_corerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
