# Generated by Django 5.0.6 on 2024-07-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_notes_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='corerequisites',
            new_name='corequisites',
        ),
    ]
