# Generated by Django 5.0.6 on 2024-07-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_rename_corerequisites_notes_corequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
