# Generated by Django 5.0.6 on 2024-07-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_notes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='level',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
