# Generated by Django 5.0.6 on 2024-07-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='media/logo.png', upload_to='profile_photos/'),
        ),
    ]
