# Generated by Django 5.0.6 on 2024-07-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
