# Generated by Django 5.0.6 on 2024-07-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default='None provided'),
        ),
        migrations.AddField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
