# Generated by Django 5.0.6 on 2024-07-18 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_remove_orders_order_date_orders_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal')], max_length=50),
        ),
    ]
