# Generated by Django 5.0.6 on 2024-07-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_alter_orders_options_remove_orders_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
