# Generated by Django 5.0.6 on 2024-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_alter_orders_options_alter_orders_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('paypal', 'PayPal')], max_length=50),
        ),
    ]
