name: Deploy to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your runtime.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      run: python manage.py collectstatic --noinput
      env:
        DJANGO_SETTINGS_MODULE: final.settings  # Replace with your actual settings module

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dereeplugged'  # This should match your Azure Web App name exactly
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}